// ⚠️  GENERATED FILE - DO NOT EDIT
// This file is automatically generated by 'prisma contract emit'.
// To regenerate, run: prisma contract emit
import type {
  Bit,
  Char,
  CodecTypes as PgTypes,
  Interval,
  JsonValue,
  Numeric,
  Time,
  TimeString,
  Timestamp,
  TimestampString,
  Timestamptz,
  TimestamptzString,
  Timetz,
  VarBit,
  Varchar,
} from '@prisma/orm-postgres/target/codec-types';
import type { QueryOperationTypes as PgTargetQueryOps } from '@prisma/orm-postgres/target/operation-types';

import type {
  ContractWithTypeMaps,
  RelationKeys,
  TypeMaps as TypeMapsType,
} from '@prisma/orm-postgres/family-contract/types';
import type {
  Contract as ContractType,
  ExecutionHashBase,
  NamespaceId,
  ProfileHashBase,
  StorageHashBase,
} from '@prisma/orm-postgres/contract/types';

export type StorageHash =
  StorageHashBase<'3cb202010b8ebe142dd2acf2d6c7765f9174b96ee6ae3a273cbb983fbdc7db8f'>;
export type ExecutionHash =
  ExecutionHashBase<'ca59eaf4fcf87bc85fd6c0638f7a90748f506a8c8f99ef2bba276db47fcba1a9'>;
export type ProfileHash =
  ProfileHashBase<'3916f444a8a17ad749191acf9e08dad97d1a327b88c2f1d45d12f240296aa8b2'>;

export type CodecTypes = PgTypes;
export type LaneCodecTypes = CodecTypes;
export type QueryOperationTypes = PgTargetQueryOps<CodecTypes>;
export type AggregateTypes = {
  readonly avg: {
    readonly byCodec: {
      readonly 'pg/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'sql/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
    };
  };
  readonly avgDecimal: {
    readonly byCodec: {
      readonly 'pg/int@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
    };
  };
  readonly count: {
    readonly byCodec: {};
    readonly withoutInput: { readonly output: 'pg/int8number@1'; readonly nullable: false };
    readonly anyInput: { readonly output: 'pg/int8number@1'; readonly nullable: false };
  };
  readonly countBigInt: {
    readonly byCodec: {};
    readonly withoutInput: { readonly output: 'pg/int8@1'; readonly nullable: false };
    readonly anyInput: { readonly output: 'pg/int8@1'; readonly nullable: false };
  };
  readonly max: {
    readonly byCodec: {
      readonly 'pg/char@1': { readonly output: 'pg/char@1'; readonly nullable: true };
      readonly 'pg/date-string@1': { readonly output: 'pg/date-string@1'; readonly nullable: true };
      readonly 'pg/date-temporal@1': {
        readonly output: 'pg/date-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/enum@1': { readonly output: 'pg/enum@1'; readonly nullable: true };
      readonly 'pg/float@1': { readonly output: 'pg/float@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float4@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/inet@1': { readonly output: 'pg/inet@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/int@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int2@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int4@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/text-array@1': { readonly output: 'pg/text-array@1'; readonly nullable: true };
      readonly 'pg/text@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/time-string@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': {
        readonly output: 'pg/time-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-string@1': {
        readonly output: 'pg/timestamp-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-temporal@1': {
        readonly output: 'pg/timestamp-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-date@1': {
        readonly output: 'pg/timestamptz-date@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-string@1': {
        readonly output: 'pg/timestamptz-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-temporal@1': {
        readonly output: 'pg/timestamptz-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timetz@1': { readonly output: 'pg/timetz@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'pg/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'sql/char@1': { readonly output: 'sql/char@1'; readonly nullable: true };
      readonly 'sql/float@1': { readonly output: 'sql/float@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'sql/int@1'; readonly nullable: true };
      readonly 'sql/text@1': { readonly output: 'sql/text@1'; readonly nullable: true };
      readonly 'sql/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
    };
  };
  readonly min: {
    readonly byCodec: {
      readonly 'pg/char@1': { readonly output: 'pg/char@1'; readonly nullable: true };
      readonly 'pg/date-string@1': { readonly output: 'pg/date-string@1'; readonly nullable: true };
      readonly 'pg/date-temporal@1': {
        readonly output: 'pg/date-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/enum@1': { readonly output: 'pg/enum@1'; readonly nullable: true };
      readonly 'pg/float@1': { readonly output: 'pg/float@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float4@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/inet@1': { readonly output: 'pg/inet@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/int@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int2@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int4@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/text-array@1': { readonly output: 'pg/text-array@1'; readonly nullable: true };
      readonly 'pg/text@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/time-string@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': {
        readonly output: 'pg/time-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-string@1': {
        readonly output: 'pg/timestamp-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-temporal@1': {
        readonly output: 'pg/timestamp-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-date@1': {
        readonly output: 'pg/timestamptz-date@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-string@1': {
        readonly output: 'pg/timestamptz-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-temporal@1': {
        readonly output: 'pg/timestamptz-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timetz@1': { readonly output: 'pg/timetz@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'pg/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'sql/char@1': { readonly output: 'sql/char@1'; readonly nullable: true };
      readonly 'sql/float@1': { readonly output: 'sql/float@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'sql/int@1'; readonly nullable: true };
      readonly 'sql/text@1': { readonly output: 'sql/text@1'; readonly nullable: true };
      readonly 'sql/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
    };
  };
  readonly sum: {
    readonly byCodec: {
      readonly 'pg/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float4@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'sql/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
    };
  };
  readonly sumBigInt: {
    readonly byCodec: {
      readonly 'pg/int@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/unboundedint@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/unboundedint@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'sql/int@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
    };
  };
};
type DefaultLiteralValue<CodecId extends string, Encoded> = CodecId extends keyof CodecTypes
  ? Encoded extends CodecTypes[CodecId]['json']
    ? Encoded
    : CodecTypes[CodecId]['json']
  : Encoded;

export type FieldOutputTypes = {
  readonly public: {
    readonly Comment: {
      readonly cmt_content: CodecTypes['pg/text@1']['output'];
      readonly cmt_created_at: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly cmt_id: CodecTypes['pg/uuid@1']['output'];
      readonly cmt_post_id: CodecTypes['pg/uuid@1']['output'];
      readonly cmt_updated_at: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly cmt_user_id: CodecTypes['pg/uuid@1']['output'];
    };
    readonly Follow: {
      readonly flw_created_at: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly flw_follower_id: CodecTypes['pg/uuid@1']['output'];
      readonly flw_following_id: CodecTypes['pg/uuid@1']['output'];
      readonly flw_id: CodecTypes['pg/uuid@1']['output'];
    };
    readonly Like: {
      readonly lik_created_at: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly lik_id: CodecTypes['pg/uuid@1']['output'];
      readonly lik_post_id: CodecTypes['pg/uuid@1']['output'];
      readonly lik_user_id: CodecTypes['pg/uuid@1']['output'];
    };
    readonly Post: {
      readonly pst_caption: CodecTypes['pg/text@1']['output'] | null;
      readonly pst_created_at: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly pst_id: CodecTypes['pg/uuid@1']['output'];
      readonly pst_updated_at: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly pst_user_id: CodecTypes['pg/uuid@1']['output'];
    };
    readonly PostImage: {
      readonly pim_created_at: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly pim_file_size: CodecTypes['pg/int8@1']['output'];
      readonly pim_height: CodecTypes['pg/int4@1']['output'];
      readonly pim_id: CodecTypes['pg/uuid@1']['output'];
      readonly pim_mime_type: Varchar<50>;
      readonly pim_position: CodecTypes['pg/int4@1']['output'];
      readonly pim_post_id: CodecTypes['pg/uuid@1']['output'];
      readonly pim_url: CodecTypes['pg/text@1']['output'];
      readonly pim_width: CodecTypes['pg/int4@1']['output'];
    };
    readonly User: {
      readonly usr_avatar_url: CodecTypes['pg/text@1']['output'] | null;
      readonly usr_bio: Varchar<150> | null;
      readonly usr_created_at: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly usr_display_name: Varchar<100>;
      readonly usr_email: Varchar<255>;
      readonly usr_id: CodecTypes['pg/uuid@1']['output'];
      readonly usr_password_hash: Varchar<255>;
      readonly usr_updated_at: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly usr_username: Varchar<30>;
    };
  };
};
export type FieldInputTypes = {
  readonly public: {
    readonly Comment: {
      readonly cmt_content: CodecTypes['pg/text@1']['input'];
      readonly cmt_created_at: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly cmt_id: CodecTypes['pg/uuid@1']['input'];
      readonly cmt_post_id: CodecTypes['pg/uuid@1']['input'];
      readonly cmt_updated_at: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly cmt_user_id: CodecTypes['pg/uuid@1']['input'];
    };
    readonly Follow: {
      readonly flw_created_at: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly flw_follower_id: CodecTypes['pg/uuid@1']['input'];
      readonly flw_following_id: CodecTypes['pg/uuid@1']['input'];
      readonly flw_id: CodecTypes['pg/uuid@1']['input'];
    };
    readonly Like: {
      readonly lik_created_at: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly lik_id: CodecTypes['pg/uuid@1']['input'];
      readonly lik_post_id: CodecTypes['pg/uuid@1']['input'];
      readonly lik_user_id: CodecTypes['pg/uuid@1']['input'];
    };
    readonly Post: {
      readonly pst_caption: CodecTypes['pg/text@1']['input'] | null;
      readonly pst_created_at: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly pst_id: CodecTypes['pg/uuid@1']['input'];
      readonly pst_updated_at: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly pst_user_id: CodecTypes['pg/uuid@1']['input'];
    };
    readonly PostImage: {
      readonly pim_created_at: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly pim_file_size: CodecTypes['pg/int8@1']['input'];
      readonly pim_height: CodecTypes['pg/int4@1']['input'];
      readonly pim_id: CodecTypes['pg/uuid@1']['input'];
      readonly pim_mime_type: CodecTypes['sql/varchar@1']['input'];
      readonly pim_position: CodecTypes['pg/int4@1']['input'];
      readonly pim_post_id: CodecTypes['pg/uuid@1']['input'];
      readonly pim_url: CodecTypes['pg/text@1']['input'];
      readonly pim_width: CodecTypes['pg/int4@1']['input'];
    };
    readonly User: {
      readonly usr_avatar_url: CodecTypes['pg/text@1']['input'] | null;
      readonly usr_bio: CodecTypes['sql/varchar@1']['input'] | null;
      readonly usr_created_at: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly usr_display_name: CodecTypes['sql/varchar@1']['input'];
      readonly usr_email: CodecTypes['sql/varchar@1']['input'];
      readonly usr_id: CodecTypes['pg/uuid@1']['input'];
      readonly usr_password_hash: CodecTypes['sql/varchar@1']['input'];
      readonly usr_updated_at: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly usr_username: CodecTypes['sql/varchar@1']['input'];
    };
  };
};
export type StorageColumnTypes = {
  readonly public: {
    readonly comments: {
      readonly cmt_content: CodecTypes['pg/text@1']['output'];
      readonly cmt_created_at: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly cmt_id: CodecTypes['pg/uuid@1']['output'];
      readonly cmt_post_id: CodecTypes['pg/uuid@1']['output'];
      readonly cmt_updated_at: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly cmt_user_id: CodecTypes['pg/uuid@1']['output'];
    };
    readonly follows: {
      readonly flw_created_at: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly flw_follower_id: CodecTypes['pg/uuid@1']['output'];
      readonly flw_following_id: CodecTypes['pg/uuid@1']['output'];
      readonly flw_id: CodecTypes['pg/uuid@1']['output'];
    };
    readonly likes: {
      readonly lik_created_at: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly lik_id: CodecTypes['pg/uuid@1']['output'];
      readonly lik_post_id: CodecTypes['pg/uuid@1']['output'];
      readonly lik_user_id: CodecTypes['pg/uuid@1']['output'];
    };
    readonly post_images: {
      readonly pim_created_at: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly pim_file_size: CodecTypes['pg/int8@1']['output'];
      readonly pim_height: CodecTypes['pg/int4@1']['output'];
      readonly pim_id: CodecTypes['pg/uuid@1']['output'];
      readonly pim_mime_type: Varchar<50>;
      readonly pim_position: CodecTypes['pg/int4@1']['output'];
      readonly pim_post_id: CodecTypes['pg/uuid@1']['output'];
      readonly pim_url: CodecTypes['pg/text@1']['output'];
      readonly pim_width: CodecTypes['pg/int4@1']['output'];
    };
    readonly posts: {
      readonly pst_caption: CodecTypes['pg/text@1']['output'] | null;
      readonly pst_created_at: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly pst_id: CodecTypes['pg/uuid@1']['output'];
      readonly pst_updated_at: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly pst_user_id: CodecTypes['pg/uuid@1']['output'];
    };
    readonly users: {
      readonly usr_avatar_url: CodecTypes['pg/text@1']['output'] | null;
      readonly usr_bio: Varchar<150> | null;
      readonly usr_created_at: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly usr_display_name: Varchar<100>;
      readonly usr_email: Varchar<255>;
      readonly usr_id: CodecTypes['pg/uuid@1']['output'];
      readonly usr_password_hash: Varchar<255>;
      readonly usr_updated_at: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly usr_username: Varchar<30>;
    };
  };
};
export type StorageColumnInputTypes = {
  readonly public: {
    readonly comments: {
      readonly cmt_content: CodecTypes['pg/text@1']['input'];
      readonly cmt_created_at: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly cmt_id: CodecTypes['pg/uuid@1']['input'];
      readonly cmt_post_id: CodecTypes['pg/uuid@1']['input'];
      readonly cmt_updated_at: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly cmt_user_id: CodecTypes['pg/uuid@1']['input'];
    };
    readonly follows: {
      readonly flw_created_at: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly flw_follower_id: CodecTypes['pg/uuid@1']['input'];
      readonly flw_following_id: CodecTypes['pg/uuid@1']['input'];
      readonly flw_id: CodecTypes['pg/uuid@1']['input'];
    };
    readonly likes: {
      readonly lik_created_at: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly lik_id: CodecTypes['pg/uuid@1']['input'];
      readonly lik_post_id: CodecTypes['pg/uuid@1']['input'];
      readonly lik_user_id: CodecTypes['pg/uuid@1']['input'];
    };
    readonly post_images: {
      readonly pim_created_at: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly pim_file_size: CodecTypes['pg/int8@1']['input'];
      readonly pim_height: CodecTypes['pg/int4@1']['input'];
      readonly pim_id: CodecTypes['pg/uuid@1']['input'];
      readonly pim_mime_type: CodecTypes['sql/varchar@1']['input'];
      readonly pim_position: CodecTypes['pg/int4@1']['input'];
      readonly pim_post_id: CodecTypes['pg/uuid@1']['input'];
      readonly pim_url: CodecTypes['pg/text@1']['input'];
      readonly pim_width: CodecTypes['pg/int4@1']['input'];
    };
    readonly posts: {
      readonly pst_caption: CodecTypes['pg/text@1']['input'] | null;
      readonly pst_created_at: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly pst_id: CodecTypes['pg/uuid@1']['input'];
      readonly pst_updated_at: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly pst_user_id: CodecTypes['pg/uuid@1']['input'];
    };
    readonly users: {
      readonly usr_avatar_url: CodecTypes['pg/text@1']['input'] | null;
      readonly usr_bio: CodecTypes['sql/varchar@1']['input'] | null;
      readonly usr_created_at: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly usr_display_name: CodecTypes['sql/varchar@1']['input'];
      readonly usr_email: CodecTypes['sql/varchar@1']['input'];
      readonly usr_id: CodecTypes['pg/uuid@1']['input'];
      readonly usr_password_hash: CodecTypes['sql/varchar@1']['input'];
      readonly usr_updated_at: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly usr_username: CodecTypes['sql/varchar@1']['input'];
    };
  };
};

export namespace Models {
  export type public_Comment = {
    cmt_content: CodecTypes['pg/text@1']['output'];
    cmt_created_at: CodecTypes['pg/timestamptz-string@1']['output'];
    cmt_id: CodecTypes['pg/uuid@1']['output'];
    cmt_post_id: CodecTypes['pg/uuid@1']['output'];
    cmt_updated_at: CodecTypes['pg/timestamptz-string@1']['output'];
    cmt_user_id: CodecTypes['pg/uuid@1']['output'];
    post: public_Post;
    user: public_User;
    readonly [RelationKeys]?: 'post' | 'user';
  };
  export type public_Follow = {
    flw_created_at: CodecTypes['pg/timestamptz-string@1']['output'];
    flw_follower_id: CodecTypes['pg/uuid@1']['output'];
    flw_following_id: CodecTypes['pg/uuid@1']['output'];
    flw_id: CodecTypes['pg/uuid@1']['output'];
    follower: public_User;
    following: public_User;
    readonly [RelationKeys]?: 'follower' | 'following';
  };
  export type public_Like = {
    lik_created_at: CodecTypes['pg/timestamptz-string@1']['output'];
    lik_id: CodecTypes['pg/uuid@1']['output'];
    lik_post_id: CodecTypes['pg/uuid@1']['output'];
    lik_user_id: CodecTypes['pg/uuid@1']['output'];
    post: public_Post;
    user: public_User;
    readonly [RelationKeys]?: 'post' | 'user';
  };
  export type public_Post = {
    pst_caption: CodecTypes['pg/text@1']['output'] | null;
    pst_created_at: CodecTypes['pg/timestamptz-string@1']['output'];
    pst_id: CodecTypes['pg/uuid@1']['output'];
    pst_updated_at: CodecTypes['pg/timestamptz-string@1']['output'];
    pst_user_id: CodecTypes['pg/uuid@1']['output'];
    comments: public_Comment[];
    images: public_PostImage[];
    likes: public_Like[];
    user: public_User;
    readonly [RelationKeys]?: 'comments' | 'images' | 'likes' | 'user';
  };
  export type public_PostImage = {
    pim_created_at: CodecTypes['pg/timestamptz-string@1']['output'];
    pim_file_size: CodecTypes['pg/int8@1']['output'];
    pim_height: CodecTypes['pg/int4@1']['output'];
    pim_id: CodecTypes['pg/uuid@1']['output'];
    pim_mime_type: Varchar<50>;
    pim_position: CodecTypes['pg/int4@1']['output'];
    pim_post_id: CodecTypes['pg/uuid@1']['output'];
    pim_url: CodecTypes['pg/text@1']['output'];
    pim_width: CodecTypes['pg/int4@1']['output'];
    post: public_Post;
    readonly [RelationKeys]?: 'post';
  };
  export type public_User = {
    usr_avatar_url: CodecTypes['pg/text@1']['output'] | null;
    usr_bio: Varchar<150> | null;
    usr_created_at: CodecTypes['pg/timestamptz-string@1']['output'];
    usr_display_name: Varchar<100>;
    usr_email: Varchar<255>;
    usr_id: CodecTypes['pg/uuid@1']['output'];
    usr_password_hash: Varchar<255>;
    usr_updated_at: CodecTypes['pg/timestamptz-string@1']['output'];
    usr_username: Varchar<30>;
    comments: public_Comment[];
    followers: public_Follow[];
    following: public_Follow[];
    likes: public_Like[];
    posts: public_Post[];
    readonly [RelationKeys]?: 'comments' | 'followers' | 'following' | 'likes' | 'posts';
  };
}

export declare const models: {
  public: {
    Comment: Models.public_Comment;
    Follow: Models.public_Follow;
    Like: Models.public_Like;
    Post: Models.public_Post;
    PostImage: Models.public_PostImage;
    User: Models.public_User;
  };
};

export type TypeMaps = TypeMapsType<
  CodecTypes,
  QueryOperationTypes,
  FieldOutputTypes,
  FieldInputTypes,
  StorageColumnTypes,
  StorageColumnInputTypes,
  AggregateTypes
>;

type ContractBase = Omit<
  ContractType<{
    readonly namespaces: {
      readonly public: {
        readonly id: 'public';
        readonly kind: 'postgres-schema';
        readonly entries: {
          readonly table: {
            readonly comments: {
              columns: {
                readonly cmt_content: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly cmt_created_at: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-string@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
                readonly cmt_id: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                };
                readonly cmt_post_id: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                };
                readonly cmt_updated_at: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-string@1';
                  readonly nullable: false;
                };
                readonly cmt_user_id: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['cmt_id'] };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: 'comments_cmt_post_id_cmt_created_at_idx_9997157b';
                  readonly prefix: 'comments_cmt_post_id_cmt_created_at_idx';
                  readonly columns: readonly ['cmt_post_id', 'cmt_created_at'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'comments';
                    readonly columns: readonly ['cmt_post_id'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'posts';
                    readonly columns: readonly ['pst_id'];
                  };
                },
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'comments';
                    readonly columns: readonly ['cmt_user_id'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'users';
                    readonly columns: readonly ['usr_id'];
                  };
                },
              ];
            };
            readonly follows: {
              columns: {
                readonly flw_created_at: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-string@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
                readonly flw_follower_id: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                };
                readonly flw_following_id: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                };
                readonly flw_id: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['flw_id'] };
              uniques: readonly [
                { readonly columns: readonly ['flw_follower_id', 'flw_following_id'] },
              ];
              indexes: readonly [
                {
                  readonly name: 'follows_flw_following_id_idx_bc930dee';
                  readonly prefix: 'follows_flw_following_id_idx';
                  readonly columns: readonly ['flw_following_id'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'follows';
                    readonly columns: readonly ['flw_follower_id'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'users';
                    readonly columns: readonly ['usr_id'];
                  };
                },
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'follows';
                    readonly columns: readonly ['flw_following_id'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'users';
                    readonly columns: readonly ['usr_id'];
                  };
                },
              ];
            };
            readonly likes: {
              columns: {
                readonly lik_created_at: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-string@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
                readonly lik_id: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                };
                readonly lik_post_id: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                };
                readonly lik_user_id: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['lik_id'] };
              uniques: readonly [{ readonly columns: readonly ['lik_user_id', 'lik_post_id'] }];
              indexes: readonly [
                {
                  readonly name: 'likes_lik_post_id_idx_480272cd';
                  readonly prefix: 'likes_lik_post_id_idx';
                  readonly columns: readonly ['lik_post_id'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'likes';
                    readonly columns: readonly ['lik_user_id'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'users';
                    readonly columns: readonly ['usr_id'];
                  };
                },
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'likes';
                    readonly columns: readonly ['lik_post_id'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'posts';
                    readonly columns: readonly ['pst_id'];
                  };
                },
              ];
            };
            readonly post_images: {
              columns: {
                readonly pim_created_at: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-string@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
                readonly pim_file_size: {
                  readonly nativeType: 'int8';
                  readonly codecId: 'pg/int8@1';
                  readonly nullable: false;
                };
                readonly pim_height: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly pim_id: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                };
                readonly pim_mime_type: {
                  readonly nativeType: 'character varying';
                  readonly codecId: 'sql/varchar@1';
                  readonly nullable: false;
                  readonly typeParams: { readonly length: 50 };
                };
                readonly pim_position: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly pim_post_id: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                };
                readonly pim_url: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly pim_width: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['pim_id'] };
              uniques: readonly [{ readonly columns: readonly ['pim_post_id', 'pim_position'] }];
              indexes: readonly [];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'post_images';
                    readonly columns: readonly ['pim_post_id'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'posts';
                    readonly columns: readonly ['pst_id'];
                  };
                },
              ];
            };
            readonly posts: {
              columns: {
                readonly pst_caption: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly pst_created_at: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-string@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
                readonly pst_id: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                };
                readonly pst_updated_at: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-string@1';
                  readonly nullable: false;
                };
                readonly pst_user_id: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['pst_id'] };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: 'posts_pst_user_id_pst_created_at_idx_2b0cc748';
                  readonly prefix: 'posts_pst_user_id_pst_created_at_idx';
                  readonly columns: readonly ['pst_user_id', 'pst_created_at'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'posts';
                    readonly columns: readonly ['pst_user_id'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'users';
                    readonly columns: readonly ['usr_id'];
                  };
                },
              ];
            };
            readonly users: {
              columns: {
                readonly usr_avatar_url: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly usr_bio: {
                  readonly nativeType: 'character varying';
                  readonly codecId: 'sql/varchar@1';
                  readonly nullable: true;
                  readonly typeParams: { readonly length: 150 };
                };
                readonly usr_created_at: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-string@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
                readonly usr_display_name: {
                  readonly nativeType: 'character varying';
                  readonly codecId: 'sql/varchar@1';
                  readonly nullable: false;
                  readonly typeParams: { readonly length: 100 };
                };
                readonly usr_email: {
                  readonly nativeType: 'character varying';
                  readonly codecId: 'sql/varchar@1';
                  readonly nullable: false;
                  readonly typeParams: { readonly length: 255 };
                };
                readonly usr_id: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                };
                readonly usr_password_hash: {
                  readonly nativeType: 'character varying';
                  readonly codecId: 'sql/varchar@1';
                  readonly nullable: false;
                  readonly typeParams: { readonly length: 255 };
                };
                readonly usr_updated_at: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-string@1';
                  readonly nullable: false;
                };
                readonly usr_username: {
                  readonly nativeType: 'character varying';
                  readonly codecId: 'sql/varchar@1';
                  readonly nullable: false;
                  readonly typeParams: { readonly length: 30 };
                };
              };
              primaryKey: { readonly columns: readonly ['usr_id'] };
              uniques: readonly [
                { readonly columns: readonly ['usr_username'] },
                { readonly columns: readonly ['usr_email'] },
              ];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
          };
        };
      };
    };
    readonly storageHash: StorageHash;
  }>,
  'roots' | 'domain'
> & {
  readonly target: 'postgres';
  readonly targetFamily: 'sql';
  readonly roots: {
    readonly comments: { readonly namespace: 'public' & NamespaceId; readonly model: 'Comment' };
    readonly follows: { readonly namespace: 'public' & NamespaceId; readonly model: 'Follow' };
    readonly likes: { readonly namespace: 'public' & NamespaceId; readonly model: 'Like' };
    readonly post_images: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'PostImage';
    };
    readonly posts: { readonly namespace: 'public' & NamespaceId; readonly model: 'Post' };
    readonly users: { readonly namespace: 'public' & NamespaceId; readonly model: 'User' };
  };
  readonly domain: {
    readonly namespaces: {
      readonly public: {
        readonly models: {
          readonly Comment: {
            readonly fields: {
              readonly cmt_content: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly cmt_created_at: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-string@1';
                };
              };
              readonly cmt_id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly cmt_post_id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly cmt_updated_at: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-string@1';
                };
              };
              readonly cmt_user_id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
            };
            readonly relations: {
              readonly post: {
                readonly to: { readonly namespace: 'public' & NamespaceId; readonly model: 'Post' };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['cmt_post_id'];
                  readonly targetFields: readonly ['pst_id'];
                };
              };
              readonly user: {
                readonly to: { readonly namespace: 'public' & NamespaceId; readonly model: 'User' };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['cmt_user_id'];
                  readonly targetFields: readonly ['usr_id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'comments';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly cmt_content: { readonly column: 'cmt_content' };
                readonly cmt_created_at: { readonly column: 'cmt_created_at' };
                readonly cmt_id: { readonly column: 'cmt_id' };
                readonly cmt_post_id: { readonly column: 'cmt_post_id' };
                readonly cmt_updated_at: { readonly column: 'cmt_updated_at' };
                readonly cmt_user_id: { readonly column: 'cmt_user_id' };
              };
            };
          };
          readonly Follow: {
            readonly fields: {
              readonly flw_created_at: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-string@1';
                };
              };
              readonly flw_follower_id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly flw_following_id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly flw_id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
            };
            readonly relations: {
              readonly follower: {
                readonly to: { readonly namespace: 'public' & NamespaceId; readonly model: 'User' };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['flw_follower_id'];
                  readonly targetFields: readonly ['usr_id'];
                };
              };
              readonly following: {
                readonly to: { readonly namespace: 'public' & NamespaceId; readonly model: 'User' };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['flw_following_id'];
                  readonly targetFields: readonly ['usr_id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'follows';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly flw_created_at: { readonly column: 'flw_created_at' };
                readonly flw_follower_id: { readonly column: 'flw_follower_id' };
                readonly flw_following_id: { readonly column: 'flw_following_id' };
                readonly flw_id: { readonly column: 'flw_id' };
              };
            };
          };
          readonly Like: {
            readonly fields: {
              readonly lik_created_at: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-string@1';
                };
              };
              readonly lik_id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly lik_post_id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly lik_user_id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
            };
            readonly relations: {
              readonly post: {
                readonly to: { readonly namespace: 'public' & NamespaceId; readonly model: 'Post' };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['lik_post_id'];
                  readonly targetFields: readonly ['pst_id'];
                };
              };
              readonly user: {
                readonly to: { readonly namespace: 'public' & NamespaceId; readonly model: 'User' };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['lik_user_id'];
                  readonly targetFields: readonly ['usr_id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'likes';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly lik_created_at: { readonly column: 'lik_created_at' };
                readonly lik_id: { readonly column: 'lik_id' };
                readonly lik_post_id: { readonly column: 'lik_post_id' };
                readonly lik_user_id: { readonly column: 'lik_user_id' };
              };
            };
          };
          readonly Post: {
            readonly fields: {
              readonly pst_caption: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly pst_created_at: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-string@1';
                };
              };
              readonly pst_id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly pst_updated_at: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-string@1';
                };
              };
              readonly pst_user_id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
            };
            readonly relations: {
              readonly comments: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Comment';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['pst_id'];
                  readonly targetFields: readonly ['cmt_post_id'];
                };
              };
              readonly images: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'PostImage';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['pst_id'];
                  readonly targetFields: readonly ['pim_post_id'];
                };
              };
              readonly likes: {
                readonly to: { readonly namespace: 'public' & NamespaceId; readonly model: 'Like' };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['pst_id'];
                  readonly targetFields: readonly ['lik_post_id'];
                };
              };
              readonly user: {
                readonly to: { readonly namespace: 'public' & NamespaceId; readonly model: 'User' };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['pst_user_id'];
                  readonly targetFields: readonly ['usr_id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'posts';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly pst_caption: { readonly column: 'pst_caption' };
                readonly pst_created_at: { readonly column: 'pst_created_at' };
                readonly pst_id: { readonly column: 'pst_id' };
                readonly pst_updated_at: { readonly column: 'pst_updated_at' };
                readonly pst_user_id: { readonly column: 'pst_user_id' };
              };
            };
          };
          readonly PostImage: {
            readonly fields: {
              readonly pim_created_at: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-string@1';
                };
              };
              readonly pim_file_size: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int8@1' };
              };
              readonly pim_height: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly pim_id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly pim_mime_type: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'sql/varchar@1';
                  readonly typeParams: { readonly length: 50 };
                };
              };
              readonly pim_position: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly pim_post_id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly pim_url: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly pim_width: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
            };
            readonly relations: {
              readonly post: {
                readonly to: { readonly namespace: 'public' & NamespaceId; readonly model: 'Post' };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['pim_post_id'];
                  readonly targetFields: readonly ['pst_id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'post_images';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly pim_created_at: { readonly column: 'pim_created_at' };
                readonly pim_file_size: { readonly column: 'pim_file_size' };
                readonly pim_height: { readonly column: 'pim_height' };
                readonly pim_id: { readonly column: 'pim_id' };
                readonly pim_mime_type: { readonly column: 'pim_mime_type' };
                readonly pim_position: { readonly column: 'pim_position' };
                readonly pim_post_id: { readonly column: 'pim_post_id' };
                readonly pim_url: { readonly column: 'pim_url' };
                readonly pim_width: { readonly column: 'pim_width' };
              };
            };
          };
          readonly User: {
            readonly fields: {
              readonly usr_avatar_url: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly usr_bio: {
                readonly nullable: true;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'sql/varchar@1';
                  readonly typeParams: { readonly length: 150 };
                };
              };
              readonly usr_created_at: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-string@1';
                };
              };
              readonly usr_display_name: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'sql/varchar@1';
                  readonly typeParams: { readonly length: 100 };
                };
              };
              readonly usr_email: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'sql/varchar@1';
                  readonly typeParams: { readonly length: 255 };
                };
              };
              readonly usr_id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly usr_password_hash: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'sql/varchar@1';
                  readonly typeParams: { readonly length: 255 };
                };
              };
              readonly usr_updated_at: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-string@1';
                };
              };
              readonly usr_username: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'sql/varchar@1';
                  readonly typeParams: { readonly length: 30 };
                };
              };
            };
            readonly relations: {
              readonly comments: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Comment';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['usr_id'];
                  readonly targetFields: readonly ['cmt_user_id'];
                };
              };
              readonly followers: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Follow';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['usr_id'];
                  readonly targetFields: readonly ['flw_following_id'];
                };
              };
              readonly following: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Follow';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['usr_id'];
                  readonly targetFields: readonly ['flw_follower_id'];
                };
              };
              readonly likes: {
                readonly to: { readonly namespace: 'public' & NamespaceId; readonly model: 'Like' };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['usr_id'];
                  readonly targetFields: readonly ['lik_user_id'];
                };
              };
              readonly posts: {
                readonly to: { readonly namespace: 'public' & NamespaceId; readonly model: 'Post' };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['usr_id'];
                  readonly targetFields: readonly ['pst_user_id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'users';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly usr_avatar_url: { readonly column: 'usr_avatar_url' };
                readonly usr_bio: { readonly column: 'usr_bio' };
                readonly usr_created_at: { readonly column: 'usr_created_at' };
                readonly usr_display_name: { readonly column: 'usr_display_name' };
                readonly usr_email: { readonly column: 'usr_email' };
                readonly usr_id: { readonly column: 'usr_id' };
                readonly usr_password_hash: { readonly column: 'usr_password_hash' };
                readonly usr_updated_at: { readonly column: 'usr_updated_at' };
                readonly usr_username: { readonly column: 'usr_username' };
              };
            };
          };
        };
      };
    };
  };
  readonly capabilities: {
    readonly postgres: {
      readonly distinctOn: true;
      readonly jsonAgg: true;
      readonly lateral: true;
      readonly limit: true;
      readonly orderBy: true;
      readonly returning: true;
    };
    readonly sql: {
      readonly checkConstraint: true;
      readonly defaultInInsert: true;
      readonly enums: true;
      readonly insertOnConflictSkip: true;
      readonly insertOnConflictWithoutTarget: true;
      readonly lateral: true;
      readonly returning: true;
      readonly scalarList: true;
    };
  };
  readonly extensions: {};
  readonly execution: {
    readonly executionHash: ExecutionHash;
    readonly mutations: {
      readonly defaults: readonly [
        {
          readonly onCreate: { readonly id: 'uuidv4'; readonly kind: 'generator' };
          readonly ref: {
            readonly column: 'cmt_id';
            readonly namespace: 'public';
            readonly table: 'comments';
          };
        },
        {
          readonly onCreate: { readonly id: 'timestampNow'; readonly kind: 'generator' };
          readonly onUpdate: { readonly id: 'timestampNow'; readonly kind: 'generator' };
          readonly ref: {
            readonly column: 'cmt_updated_at';
            readonly namespace: 'public';
            readonly table: 'comments';
          };
        },
        {
          readonly onCreate: { readonly id: 'uuidv4'; readonly kind: 'generator' };
          readonly ref: {
            readonly column: 'flw_id';
            readonly namespace: 'public';
            readonly table: 'follows';
          };
        },
        {
          readonly onCreate: { readonly id: 'uuidv4'; readonly kind: 'generator' };
          readonly ref: {
            readonly column: 'lik_id';
            readonly namespace: 'public';
            readonly table: 'likes';
          };
        },
        {
          readonly onCreate: { readonly id: 'uuidv4'; readonly kind: 'generator' };
          readonly ref: {
            readonly column: 'pim_id';
            readonly namespace: 'public';
            readonly table: 'post_images';
          };
        },
        {
          readonly onCreate: { readonly id: 'uuidv4'; readonly kind: 'generator' };
          readonly ref: {
            readonly column: 'pst_id';
            readonly namespace: 'public';
            readonly table: 'posts';
          };
        },
        {
          readonly onCreate: { readonly id: 'timestampNow'; readonly kind: 'generator' };
          readonly onUpdate: { readonly id: 'timestampNow'; readonly kind: 'generator' };
          readonly ref: {
            readonly column: 'pst_updated_at';
            readonly namespace: 'public';
            readonly table: 'posts';
          };
        },
        {
          readonly onCreate: { readonly id: 'uuidv4'; readonly kind: 'generator' };
          readonly ref: {
            readonly column: 'usr_id';
            readonly namespace: 'public';
            readonly table: 'users';
          };
        },
        {
          readonly onCreate: { readonly id: 'timestampNow'; readonly kind: 'generator' };
          readonly onUpdate: { readonly id: 'timestampNow'; readonly kind: 'generator' };
          readonly ref: {
            readonly column: 'usr_updated_at';
            readonly namespace: 'public';
            readonly table: 'users';
          };
        },
      ];
    };
  };
  readonly meta: {};

  readonly profileHash: ProfileHash;
};

export type Contract = ContractWithTypeMaps<ContractBase, TypeMaps>;

export type Namespaces = Contract['storage']['namespaces'];
